version: "3.7"

services:
  app:
    build: .
    image: image_name:${VERSION}
    ports:
      - 10000:8080

    restart: "unless-stopped"

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    # volumes:
    #   - type: bind
    #     source: ./log
    #     target: /app/log
