version: '3.8'
services:
  mongodb:
    restart: unless-stopped
    image: mongo:8.0-rc
    ports:
      - '27017:27017'
    volumes:
      - ./volumes/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: test
