FROM python:3.10-slim

COPY ./requirements.txt /tmp/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /tmp/requirements.txt

WORKDIR /app

COPY . .

ENTRYPOINT uvicorn app:app --host 0.0.0.0 --port 80
