version: '3'

x-common: &common
  restart: unless-stopped
  volumes:
    - ./logs:/app/logs
    - ./res:/app/res
  env_file:
    - .env

services:
  api:
    image: azurecr.io/myimage-ui-dev:latest
    <<: *common
    ports:
      - 7373:80
  ui:
    image: azurecr.io/myimage-streamlit-dev:latest
    <<: *common
    ports:
      - 7374:8501
  queue:
    image: azurecr.io/myimage-queue-dev:latest
    <<: *common
