name: Build and Push to ACR
on:
  push:
    branches:
      - 'main'
      - 'staging'
      - 'dev'
jobs:
  build:
    name: 'Build and Push to ACR'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_ADDRESS }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Build and Push to ACR
        uses: docker/build-push-action@v5
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ secrets.ACR_ADDRESS }}/docker-image-name-${{ steps.extract_branch.outputs.branch }}:latest
          file: Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: executing remote ssh commands
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.HOST }}
          username: azureuser
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: sh /home/azureuser/services/-${{ steps.extract_branch.outputs.branch }}/update.sh
